Updated to 0.1.3 with the latest will-paginate gem version at this date
patricklindsay/will_paginate-materialize pull request #7
Opened 2018-06-26 23:30 UTC by mldoscar

It would be great to pull these changes because the **will_paginate-materialize** gemspec file currently has an old **will_paginate** version dependency. 
Nevertheless, I already tested the changes with **will_paginate** version **3.1.6** and it works like charm! After that, you could build it and pull the gem package into **RubyGems.org**

Without any other mention left I send you my best regards
Sincerely,
Oscar

2019-02-21 18:34 UTC, adamwgriffin commented
@patricklindsay any plans on merging this, or the other open pull request to update to the newer version of will_paginate? The older version uses features of ruby which are now deprecated. See comments on the release for version 3.1.16 https://github.com/mislav/will_paginate/releases/tag/v3.1.6

2019-02-24 08:42 UTC, patricklindsay requested changes
This looks to be a breaking change. If you can update `lib/materialize_pagination/version.rb` to 1.0.0 and the CHANGLOG then I'll approve this and publish the new version.

2019-02-24 21:16 UTC, mldoscar commented
> This looks to be a breaking change. If you can update `lib/materialize_pagination/version.rb` to 1.0.0 and the CHANGLOG then I'll approve this and publish the new version.

Commit has been made with the requested changes

2019-02-25 07:30 UTC, merged

2019-02-25 07:33 UTC, patricklindsay commented
v1.0.0 released. Does this fix #2 ? @mldoscar @adamwgriffin

2019-02-25 16:58 UTC, adamwgriffin commented
Thanks for merging the PR @patricklindsay! I'm not sure if it fixes #2 since I was not experiencing that particular issue.

2019-02-26 02:38 UTC, mldoscar commented
Thanks for mergin the PR @patricklindsay
I'm not experiencing that issue #2 either. Also the code looks like tags are redering in the correct order